In [1]:
import numpy as np
import scipy.linalg

In [2]:
E = np.eye(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
5*E - 1

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [-1., -1., -1., -1.,  4.]])

#### 5.2

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [5]:
det_A = np.linalg.det(A)
det_A

59.999999999999986

#### 5.3

##### 1)

In [6]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

##### 2)

In [7]:
B = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [5, 5, 5, 5], [7, 7, 7, 7]])
B

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [5, 5, 5, 5],
       [7, 7, 7, 7]])

In [8]:
rank_B = np.linalg.matrix_rank(B)
rank_B

1

#### 5.4

In [9]:
a = [1, 5]
b = [2, 8]
ab_sc = np.dot(a, b)
ab_sc

42

#### 5.5

In [10]:
a = [1, 5, 0]
b = [2, 8, 7]
c = [7, 1.5, 3]

v = np.cross(a, b)
w = np.dot(v, c)
w

228.5

#### 6.1

In [11]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

#### 6.2

In [12]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#### 6.3

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.hstack((A, B.T))
C

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

In [14]:
print(f'Matrix A rank = {np.linalg.matrix_rank(A)}')
print(f'Matrix C rank = {np.linalg.matrix_rank(C)}')

Matrix A rank = 2
Matrix C rank = 3


###### => система не имеет решений

In [15]:
np.linalg.det(A)

6.66133814775094e-16

In [16]:
A1 = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A1)

-3.0000000000000018

In [17]:
C1 = C = np.hstack((A1, B.T))
C1

array([[ 2,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

In [18]:
print(f'Matrix A1 rank = {np.linalg.matrix_rank(A1)}')
print(f'Matrix C1 rank = {np.linalg.matrix_rank(C1)}')

Matrix A1 rank = 3
Matrix C1 rank = 3


In [19]:
np.linalg.solve(A1, B.T)

array([[  9.        ],
       [-22.        ],
       [ 12.66666667]])

#### 6.4

In [20]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(f'det A = {np.linalg.det(A)}')

print(f'P = {P}')
print(f'L = {L}')
print(f'U = {U}')

det A = 432.00000000000017
P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [21]:
lu, piv = scipy.linalg.lu_factor(A)
B = [3, 15, 85]
scipy.linalg.lu_solve((lu, piv), B)

array([ 0.69444444, -1.26388889,  1.61111111])

#### 6.5

In [22]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([[1, 12]]).T
np.linalg.lstsq(A, B)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[ 1.38191882],
        [-0.18081181],
        [ 0.0202952 ]]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

#### 6.6

In [23]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 11]])
X = np.linalg.lstsq(A, B.T)
X

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[ 1.25],
        [ 0.5 ],
        [-0.25]]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

In [24]:
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [25]:
np.dot(Q, R)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
R1 = R[:2, :2]
B1 = np.dot(Q.T, B.T)[:2]
X1 = np.linalg.solve(R1, B1)
X1

array([[1.50000000e+00],
       [9.32822279e-15]])

In [27]:
X = np.append(X1, 0)
print(np.linalg.norm(X))

1.4999999999999896


#### 1

In [28]:
A = np.array([[1, 2], [3, 1], [2, 2]])
B = np.array([[500, 750, 700]])
np.linalg.lstsq(A, B.T)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[200.],
        [150.]]), array([8.53231955e-27]), 2, array([4.56516931, 1.46943158]))

#### 2

In [29]:
A = np.array([[1, 2], [3, 1], [2, 2]])
B = np.array([[500, 750, 650]])
np.linalg.lstsq(A, B.T)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[200.        ],
        [138.88888889]]),
 array([1388.88888889]),
 2,
 array([4.56516931, 1.46943158]))

#### 3

In [30]:
A = np.array([[1, 2], [3, 1], [2, 3]])
B = np.array([[500, 750, 700]])
np.linalg.lstsq(A, B.T)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[210.],
        [110.]]), array([7500.]), 2, array([5.        , 1.73205081]))

#### 4

In [31]:
A = np.array([[1, 2], [3, 1], [2, 3], [1, 5]])
B = np.array([[500, 750, 700, 850]])
np.linalg.lstsq(A, B.T)

C:\Users\7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[198.78419453],
        [126.13981763]]),
 array([9346.50455927]),
 2,
 array([6.8556546 , 2.64575131]))